"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load .env file explicitly
try:
    from dotenv import load_dotenv
    env_path = BASE_DIR / '.env'
    load_dotenv(env_path, override=True)
except ImportError:
    # Fallback if python-dotenv is not installed
    import os
    env_path = BASE_DIR / '.env'
    if env_path.exists():
        with open(env_path, 'r', encoding='utf-8') as f:
            for line in f:
                line = line.strip()
                if not line or line.startswith('#'): continue
                if '=' in line:
                    key, value = line.split('=', 1)
                    os.environ[key.strip()] = value.strip()

import os


# SECURITY WARNING: keep the secret key used in production secret!
# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY', 'django-insecure-w4i1wehn)hnc*l@&z+(zo+kny$k0mu1udux*u$kcu*mh*7%o1j')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG', 'False') == 'True'

# ALLOWED_HOSTS: include localhost for development, and any onrender.com hostname
# provided via the ALLOWED_HOSTS env var.  When running on Render the hostname
# is *always* <app>.onrender.com, so we include that as a safe fallback.
_raw_hosts = os.getenv('ALLOWED_HOSTS', '')
ALLOWED_HOSTS = [h.strip() for h in _raw_hosts.split(',') if h.strip()] if _raw_hosts else ['127.0.0.1', 'localhost']

# Trusted origins for CSRF protection behind HTTPS proxies (comma-separated,
# e.g. https://inventobots.onrender.com).
# Auto-detect Render hostname from ALLOWED_HOSTS when not explicitly set.
CSRF_TRUSTED_ORIGINS = [
    o for o in os.getenv('CSRF_TRUSTED_ORIGINS', '').split(',') if o
]
if not CSRF_TRUSTED_ORIGINS:
    for _host in ALLOWED_HOSTS:
        if _host.endswith('.onrender.com'):
            CSRF_TRUSTED_ORIGINS.append(f'https://{_host}')



# Application definition

INSTALLED_APPS = [
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',
    'admin_interface',
    'colorfield',
    'rest_framework',
    'corsheaders',
    'core',
    'study_materials',  # New app for study materials
    'certifications',
    'parents',
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.google',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware', # Serves collected static files in production
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'allauth.account.middleware.AccountMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases
#
# Production: set DATABASE_URL env var (e.g. from Render/Neon:
#   postgresql://user:password@host/dbname)
# Local development: falls back to the local PostgreSQL instance below.

if os.getenv('DATABASE_URL'):
    from urllib.parse import urlparse, unquote
    _db = urlparse(os.getenv('DATABASE_URL'))
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': _db.path.lstrip('/'),
            'USER': unquote(_db.username or ''),
            'PASSWORD': unquote(_db.password or ''),
            'HOST': _db.hostname or '',
            'PORT': str(_db.port or 5432),
            'CONN_MAX_AGE': 60,
            'OPTIONS': {'sslmode': os.getenv('DB_SSLMODE', 'require')},
        }
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': os.getenv('DB_NAME', 'inventobots_db'),
            'USER': os.getenv('DB_USER', 'inventobots_user'),
            'PASSWORD': os.getenv('DB_PASSWORD', ''),
            'HOST': os.getenv('DB_HOST', '127.0.0.1'),
            'PORT': os.getenv('DB_PORT', '5432'),
            'CONN_MAX_AGE': 60,
        }
    }



# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Redirect to home or login
LOGIN_URL = '/parents/login/'
LOGIN_REDIRECT_URL = 'parents:dashboard'
LOGOUT_REDIRECT_URL = 'parents:login'

SITE_ID = 1

AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend',
]

ACCOUNT_EMAIL_REQUIRED = True
ACCOUNT_USERNAME_REQUIRED = False
ACCOUNT_AUTHENTICATION_METHOD = 'email'
ACCOUNT_EMAIL_VERIFICATION = 'none'

SOCIALACCOUNT_PROVIDERS = {
    'google': {
        'SCOPE': [
            'profile',
            'email',
        ],
        'AUTH_PARAMS': {
            'access_type': 'online',
        },
        # App credentials supplied via environment variables instead of DB rows,
        # so the login page renders even when no SocialApp exists in the database.
        # Leave unset to disable working Google sign-in (button will not authenticate).
        'APP': {
            'client_id': os.getenv('GOOGLE_OAUTH_CLIENT_ID', 'demo-not-configured'),
            'secret': os.getenv('GOOGLE_OAUTH_SECRET', 'demo-not-configured'),
            'key': '',
        },
    }
}


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [BASE_DIR / 'static']
if not (BASE_DIR / 'static').exists():
    STATICFILES_DIRS = []
STATIC_ROOT = BASE_DIR / 'staticfiles' # Added for collectstatic

# WhiteNoise: serve static files efficiently in production
STORAGES = {
    'default': {'BACKEND': 'django.core.files.storage.FileSystemStorage'},
    'staticfiles': {'BACKEND': 'whitenoise.storage.CompressedManifestStaticFilesStorage'},
}

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Security Settings
SESSION_EXPIRE_AT_BROWSER_CLOSE = True
SECURE_BROWSER_XSS_FILTER = True
SECURE_CONTENT_TYPE_NOSNIFF = True
CSRF_COOKIE_SECURE = not DEBUG
SESSION_COOKIE_SECURE = not DEBUG
# SECURE_SSL_REDIRECT: defaults to True in production (DEBUG=False).
# When behind Render's load balancer, SECURE_PROXY_SSL_HEADER ensures Django
# recognises the original HTTPS request so it does NOT create a redirect loop.
SECURE_SSL_REDIRECT = os.getenv('SECURE_SSL_REDIRECT', str(not DEBUG)).lower() == 'true'
# Trust Render's load balancer X-Forwarded-Proto header so Django sees HTTPS requests correctly
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
X_FRAME_OPTIONS = 'DENY'

JAZZMIN_SETTINGS = {
    "site_title": "Inventobots Admin",
    "site_header": "Inventobots Academy",
    "site_brand": "Inventobots Academy",
    "site_logo": "images/Logo.png",
    "welcome_sign": "Admin Panel",
    "copyright": "Inventobots Academy",
    "search_model": "auth.User",
    "user_avatar": None,
    # "topmenu_links": [
    #     {"name": "Home",  "url": "admin:index", "permissions": ["auth.view_user"]},
    # ],
    "show_sidebar": True,
    "navigation_expanded": True,
    "hide_apps": [],
    "hide_models": [],
    "icons": {
        "auth": "fas fa-users-cog",
        "auth.user": "fas fa-user",
        "auth.Group": "fas fa-users",
    },
    "default_icon_parents": "fas fa-chevron-circle-right",
    "default_icon_children": "fas fa-circle",
    "related_modal_active": False,
    "custom_css": "css/admin_theme.css",
    "custom_js": None,
    "show_ui_builder": False,
}

# Razorpay Configuration
RAZORPAY_KEY_ID = os.getenv('RAZORPAY_KEY_ID', 'rzp_test_YOUR_KEY_HERE')
RAZORPAY_KEY_SECRET = os.getenv('RAZORPAY_KEY_SECRET', 'YOUR_SECRET_HERE')

# Default primary key field type
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# ==============================================================================
# TEMPORARY DIAGNOSTIC CONFIGURATION (TO BE REMOVED AFTER ROOT-CAUSE IDENTIFICATION)
# Directs Django request errors and tracebacks to standard error for Render logs.
# Safe: Logs server-side only; does not expose secrets or debug pages to visitors.
# ==============================================================================
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'diagnostic_formatter': {
            'format': (
                '\n'
                '==================== [DJANGO EXCEPTION DIAGNOSTIC START] ====================\n'
                'Timestamp: %(asctime)s\n'
                'Logger: %(name)s | Level: %(levelname)s\n'
                'Message: %(message)s\n'
                '----------------------------------------------------------------------------'
            ),
        },
    },
    'handlers': {
        'render_console': {
            'class': 'logging.StreamHandler',
            'formatter': 'diagnostic_formatter',
            'stream': 'ext://sys.stderr',
        },
    },
    'root': {
        'handlers': ['render_console'],
        'level': 'INFO',
    },
    'loggers': {
        'django': {
            'handlers': ['render_console'],
            'level': 'INFO',
            'propagate': False,
        },
        'django.request': {
            'handlers': ['render_console'],
            'level': 'ERROR',
            'propagate': False,
        },
    },
}
# ==============================================================================

