release: python manage.py migrate && python manage.py collectstatic --noinput
start: python manage.py migrate --noinput && python manage.py seed_courses && python manage.py seed_hero_courses && python manage.py seed_demo_accounts && gunicorn config.wsgi:application --workers 2 --bind 0.0.0.0:$PORT
