# Generated by Django 6.0.1 on 2026-01-16 17:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CertificationCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('duration', models.CharField(help_text="e.g. '8 Weeks'", max_length=50)),
                ('level', models.CharField(help_text="e.g. 'Beginner to Advanced'", max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_id', models.CharField(db_index=True, max_length=50, unique=True)),
                ('student_name', models.CharField(max_length=200)),
                ('issue_date', models.DateField()),
                ('issued_by', models.CharField(default='Inventobots Academy', max_length=100)),
                ('status', models.CharField(choices=[('Valid', 'Valid'), ('Revoked', 'Revoked')], default='Valid', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='certifications.certificationcourse')),
            ],
        ),
    ]
