# Generated by Django 6.0.1 on 2026-01-18 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certifications', '0002_certificationcourse_image_certificationcourse_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='certificate_image',
            field=models.ImageField(blank=True, help_text='Upload the certificate image', null=True, upload_to='certificate_images/'),
        ),
    ]
