# Generated by Django 6.0.1 on 2026-02-01 05:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certifications', '0003_certificate_certificate_image'),
        ('core', '0008_badge_quiz_question_quizsubmission_topic_quiz_topic_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificationcourse',
            name='core_course',
            field=models.ForeignKey(blank=True, help_text='Link to the core course content for progress tracking', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.course'),
        ),
    ]
