# Generated by Django 6.0.1 on 2026-02-01 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certifications', '0004_certificationcourse_core_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificationcourse',
            name='whatsapp_group_link',
            field=models.URLField(blank=True, help_text='Invite link for the WhatsApp group (e.g., chat.whatsapp.com/...)'),
        ),
    ]
