# Generated by Django 6.0.1 on 2026-02-11 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certifications', '0005_certificationcourse_whatsapp_group_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='certificate_id',
            field=models.CharField(blank=True, db_index=True, help_text='Leave blank to auto-generate (e.g., INV-2026-0042)', max_length=50, unique=True),
        ),
    ]
