# Generated by Django 6.0.1 on 2026-02-11 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certifications', '0006_alter_certificate_certificate_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificationcourse',
            name='certid_position_x',
            field=models.IntegerField(default=850, help_text='X coordinate for certificate ID'),
        ),
        migrations.AddField(
            model_name='certificationcourse',
            name='certid_position_y',
            field=models.IntegerField(default=570, help_text='Y coordinate for certificate ID'),
        ),
        migrations.AddField(
            model_name='certificationcourse',
            name='certificate_template',
            field=models.ImageField(blank=True, help_text='Upload the certificate background template image (recommended: 1200×850px, landscape PNG/JPG)', null=True, upload_to='certificate_templates/'),
        ),
        migrations.AddField(
            model_name='certificationcourse',
            name='course_position_x',
            field=models.IntegerField(default=600, help_text='X coordinate for course name (center-aligned)'),
        ),
        migrations.AddField(
            model_name='certificationcourse',
            name='course_position_y',
            field=models.IntegerField(default=430, help_text='Y coordinate for course name'),
        ),
        migrations.AddField(
            model_name='certificationcourse',
            name='date_position_x',
            field=models.IntegerField(default=350, help_text='X coordinate for issue date'),
        ),
        migrations.AddField(
            model_name='certificationcourse',
            name='date_position_y',
            field=models.IntegerField(default=570, help_text='Y coordinate for issue date'),
        ),
        migrations.AddField(
            model_name='certificationcourse',
            name='detail_font_size',
            field=models.IntegerField(default=24, help_text='Font size for course name, date, and certificate ID'),
        ),
        migrations.AddField(
            model_name='certificationcourse',
            name='name_font_size',
            field=models.IntegerField(default=52, help_text='Font size for student name'),
        ),
        migrations.AddField(
            model_name='certificationcourse',
            name='name_position_x',
            field=models.IntegerField(default=600, help_text='X coordinate for student name (center-aligned)'),
        ),
        migrations.AddField(
            model_name='certificationcourse',
            name='name_position_y',
            field=models.IntegerField(default=340, help_text='Y coordinate for student name'),
        ),
        migrations.AddField(
            model_name='certificationcourse',
            name='text_color',
            field=models.CharField(default='#1a1a2e', help_text='Hex color for all text (e.g., #1a1a2e)', max_length=7),
        ),
    ]
