# Generated by Django 6.0.1 on 2026-02-11 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certifications', '0007_certificationcourse_certid_position_x_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificationcourse',
            name='detail_color',
            field=models.CharField(default='#1a1a2e', help_text='Hex color for details', max_length=7),
        ),
        migrations.AddField(
            model_name='certificationcourse',
            name='detail_font_family',
            field=models.CharField(choices=[('Inter.ttf', 'Inter (Modern Sans)'), ('Roboto.ttf', 'Roboto (Clean Sans)'), ('PlayfairDisplay.ttf', 'Playfair Display (Elegant Serif)'), ('GreatVibes.ttf', 'Great Vibes (Cursive)')], default='Inter.ttf', help_text='Font for details (optional override)', max_length=50),
        ),
        migrations.AddField(
            model_name='certificationcourse',
            name='font_family',
            field=models.CharField(choices=[('Inter.ttf', 'Inter (Modern Sans)'), ('Roboto.ttf', 'Roboto (Clean Sans)'), ('PlayfairDisplay.ttf', 'Playfair Display (Elegant Serif)'), ('GreatVibes.ttf', 'Great Vibes (Cursive)')], default='Inter.ttf', help_text='Primary font family', max_length=50),
        ),
        migrations.AddField(
            model_name='certificationcourse',
            name='name_color',
            field=models.CharField(default='#1a1a2e', help_text='Hex color for student name', max_length=7),
        ),
        migrations.AlterField(
            model_name='certificationcourse',
            name='certid_position_x',
            field=models.IntegerField(default=850),
        ),
        migrations.AlterField(
            model_name='certificationcourse',
            name='certid_position_y',
            field=models.IntegerField(default=570),
        ),
        migrations.AlterField(
            model_name='certificationcourse',
            name='course_position_x',
            field=models.IntegerField(default=600),
        ),
        migrations.AlterField(
            model_name='certificationcourse',
            name='course_position_y',
            field=models.IntegerField(default=430),
        ),
        migrations.AlterField(
            model_name='certificationcourse',
            name='date_position_x',
            field=models.IntegerField(default=350),
        ),
        migrations.AlterField(
            model_name='certificationcourse',
            name='date_position_y',
            field=models.IntegerField(default=570),
        ),
        migrations.AlterField(
            model_name='certificationcourse',
            name='detail_font_size',
            field=models.IntegerField(default=24),
        ),
        migrations.AlterField(
            model_name='certificationcourse',
            name='name_font_size',
            field=models.IntegerField(default=52),
        ),
        migrations.AlterField(
            model_name='certificationcourse',
            name='name_position_x',
            field=models.IntegerField(default=600),
        ),
        migrations.AlterField(
            model_name='certificationcourse',
            name='name_position_y',
            field=models.IntegerField(default=340),
        ),
        migrations.AlterField(
            model_name='certificationcourse',
            name='text_color',
            field=models.CharField(blank=True, default='#1a1a2e', max_length=7),
        ),
    ]
