# Generated by Django 6.0.1 on 2026-02-17 10:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certifications', '0008_certificationcourse_detail_color_and_more'),
        ('core', '0009_lesson_module_quiz_lesson_lesson_module_subject_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.course'),
        ),
    ]
