# Generated by Django 6.0.1 on 2026-01-31 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parents', '0002_student_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='level',
            field=models.IntegerField(default=1, help_text='Current student level'),
        ),
        migrations.AddField(
            model_name='student',
            name='xp',
            field=models.IntegerField(default=0, help_text='Experience points'),
        ),
    ]
