# Generated by Django 6.0.1 on 2026-02-01 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parents', '0003_student_level_student_xp'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseenrollment',
            name='is_manually_modified',
            field=models.BooleanField(default=False, help_text='If True, auto-updates for progress will be skipped.'),
        ),
        migrations.AddField(
            model_name='courseenrollment',
            name='last_activity_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
