# Generated by Django 6.0.1 on 2026-02-01 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parents', '0004_courseenrollment_is_manually_modified_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseenrollment',
            name='payment_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='courseenrollment',
            name='payment_reference',
            field=models.CharField(blank=True, help_text='Transaction ID or Reference', max_length=100),
        ),
        migrations.AddField(
            model_name='courseenrollment',
            name='payment_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed'), ('Failed', 'Failed')], default='Pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='courseenrollment',
            name='status',
            field=models.CharField(choices=[('Pending Payment', 'Pending Payment'), ('Active', 'Active'), ('Completed', 'Completed'), ('Paused', 'Paused'), ('Cancelled', 'Cancelled')], default='Pending Payment', max_length=20),
        ),
    ]
