# Generated by Django 6.0.1 on 2026-02-17 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parents', '0006_attendance_lesson_alter_attendance_course_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseenrollment',
            name='mode',
            field=models.CharField(choices=[('Online', 'Online'), ('Offline', 'Offline')], default='Online', max_length=10),
        ),
    ]
