# Generated by Django 6.0.1 on 2026-01-14 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='category',
            field=models.CharField(choices=[('ROBOTICS', 'Robotics'), ('CODING', 'Coding'), ('ABACUS', 'Abacus'), ('ACADEMIC', 'Academic'), ('OTHER', 'Other')], default='OTHER', max_length=20),
        ),
    ]
