# Generated by Django 6.0.1 on 2026-01-27 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_enrollment_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
        migrations.AddField(
            model_name='course',
            name='badge',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='color_gradient',
            field=models.CharField(default='from-blue-500 to-cyan-400', max_length=100),
        ),
        migrations.AddField(
            model_name='course',
            name='cta_primary_text',
            field=models.CharField(default='Explore', max_length=50),
        ),
        migrations.AddField(
            model_name='course',
            name='cta_primary_url',
            field=models.CharField(default='/courses/', max_length=200),
        ),
        migrations.AddField(
            model_name='course',
            name='cta_secondary_text',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='cta_secondary_url',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='display_order',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='course',
            name='highlights',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='course',
            name='is_hero_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='course',
            name='subtitle',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='tagline',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='category',
            field=models.CharField(choices=[('ROBOTICS', 'Robotics'), ('CODING', 'Coding'), ('ABACUS', 'Abacus'), ('ACADEMIC', 'Academic'), ('INVENTOWRITE', 'Inventowrite'), ('INVENTOSHASTRA', 'Inventoshastra'), ('INVENTOTHUNAI', 'Inventothunai'), ('INVENTOPHONICS', 'Inventophonics'), ('INVENTOBEADS', 'Inventobeads'), ('INVENTOHINDI', 'Inventohindi'), ('OTHER', 'Other')], default='OTHER', max_length=20),
        ),
        migrations.DeleteModel(
            name='Enrollment',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
