# Generated by Django 6.0.1 on 2026-01-27 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_userprofile_user_course_badge_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='image_url',
            field=models.URLField(blank=True, help_text='External URL for image (used if Image file is not set)', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='courses/'),
        ),
    ]
