# Generated by Django 6.0.1 on 2026-01-27 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_course_image_url_alter_course_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeroSlide',
            fields=[
            ],
            options={
                'verbose_name': 'Hero Slider Item',
                'verbose_name_plural': 'Hero Slider Items',
                'ordering': ['display_order'],
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.course',),
        ),
        migrations.AlterField(
            model_name='course',
            name='cta_primary_url',
            field=models.CharField(default='/courses/', max_length=1000),
        ),
        migrations.AlterField(
            model_name='course',
            name='cta_secondary_url',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
