# Generated by Django 6.0.1 on 2026-01-28 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_heroslide_alter_course_cta_primary_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='certification_details',
            field=models.TextField(blank=True, help_text='Details about certification', null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='duration',
            field=models.CharField(blank=True, help_text="Duration of the course (e.g., '12 Weeks')", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='mode',
            field=models.CharField(choices=[('ONLINE', 'Online'), ('OFFLINE', 'Offline'), ('HYBRID', 'Hybrid')], default='ONLINE', help_text='Mode of the course', max_length=20),
        ),
        migrations.AddField(
            model_name='course',
            name='notes',
            field=models.TextField(blank=True, help_text='Any additional notes', null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='start_date',
            field=models.DateField(blank=True, help_text='Course start date (if applicable)', null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='syllabus',
            field=models.TextField(blank=True, help_text='Detailed syllabus or topics covered', null=True),
        ),
    ]
