# Generated by Django 6.0.1 on 2026-02-17 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_lesson_module_quiz_lesson_lesson_module_subject_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='duration',
            field=models.PositiveIntegerField(default=0, help_text='Duration of the course in weeks'),
        ),
    ]
