# Generated by Django 6.0.1 on 2026-02-17 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_course_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='course_thumbnails/'),
        ),
        migrations.AddField(
            model_name='course',
            name='total_offline_classes',
            field=models.PositiveIntegerField(default=0, help_text='Total number of scheduled offline classes for attendance calculation.'),
        ),
    ]
