# Generated by Django 6.0.1 on 2026-02-18 13:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0011_course_thumbnail_course_total_offline_classes'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudyMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text="Title of the study material (e.g., 'Chapter 1 Notes')", max_length=200)),
                ('description', models.TextField(blank=True, help_text='Optional description or instructions.')),
                ('material_type', models.CharField(choices=[('PDF', 'PDF Document'), ('VIDEO', 'Video File'), ('IMAGE', 'Image'), ('ZIP', 'Zip/Archive'), ('LINK', 'External Link/Video URL'), ('OTHER', 'Other')], default='PDF', max_length=10)),
                ('file', models.FileField(blank=True, help_text='Upload the file (PDF, Video, etc.)', null=True, upload_to='study_materials/')),
                ('video_url', models.URLField(blank=True, help_text='YouTube or external video link (if not uploading a file)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(help_text='Select the course this material belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='study_materials', to='core.course')),
            ],
            options={
                'verbose_name': 'Study Material',
                'verbose_name_plural': 'Study Materials',
                'ordering': ['-created_at'],
            },
        ),
    ]
