# Generated by Django 6.0.1 on 2026-02-18 18:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study_materials', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudyMaterialFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='study_materials/files/')),
                ('description', models.CharField(blank=True, help_text='Configurable description for the file', max_length=255)),
                ('study_material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='study_materials.studymaterial')),
            ],
        ),
    ]
